jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'src/runner.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'osrs-bots'
          options: --onefile, --name 'osrs-bots', --windowed,