on:
  release:
    types: [published]

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:

      - name: (Install) python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
    
      - name: (Install) python dev tools
        shell: bash
        run: python -m pip install pip wheel setuptools
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: (Install) dependencies
        shell: bash
        run: |
          pip install pylint
          pip install pyautogui
          pip install customtkinter
          pip install osrs-python-bot

      - name: (Install) pyinstaller
        shell: bash
        run: pip install pyinstaller

      - name: (Create) Executable
        shell: bash
        run: |
          pyinstaller --onefile --windowed src/runner.py
          
          echo "✔️ Executable created successfully at _'./dist'_" >> $GITHUB_STEP_SUMMARY
          echo "  - Python version used: '3.x'" >> $GITHUB_STEP_SUMMARY
          echo "  - Python architecture used: 'x64'" >> $GITHUB_STEP_SUMMARY
  
      - name: (Upload) Executable
        id: artifact_upload
        uses: actions/upload-artifact@v3
        with:
          name: 'osrs-bots'
          path: './dist'

      - name: If executable upload success
        id: exe_uploading
        if: steps.artifact_upload.conclusion == 'success'
        shell: bash
        run: |
          echo "✔️ Executable **osrs-python-bots-runner** uploaded successfully" >> $GITHUB_STEP_SUMMARY
          echo "uploaded='true'" >> $GITHUB_OUTPUT
      
      - name: If executable upload fails
        if: failure() && steps.artifact_upload.conclusion == 'failure'
        shell: bash
        run: |
          echo "::warning title=Failed-Upload::\
            Executable couldn't upload. \
            Check available storage at: 'settings > billing > Storage for Actions and Packages'."