on:
  release:
    types: [published]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@main
        with:
          python_ver: '3.8'
          spec: 'src/runner.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'osrs-bots'
          options: --onefile, --name "osrs-bots", --windowed,